export const INSTITUTION_TYPES = {
  GENERAL_UNIVERSITY: "GENERAL_UNIVERSITY",
  ENGINEERING_UNIVERSITY: "ENGINEERING_UNIVERSITY",
  SCIENCE_TECHNOLOGY_UNIVERSITY: "SCIENCE_TECHNOLOGY_UNIVERSITY",
  MEDICAL_COLLEGE: "MEDICAL_COLLEGE",
  COLLEGE: "COLLEGE",
  POLYTECHNIC_INSTITUTE: "POLYTECHNIC_INSTITUTE",
  SCHOOL: "SCHOOL",
  OTHER: "OTHER",
};

export const INSTITUTION_CATEGORY = {
  PUBLIC: "PUBLIC", // পাবলিক ভার্সিটি (BUET, DU)
  PRIVATE: "PRIVATE", // প্রাইভেট (NSU, BRAC)
  NATIONAL: "NATIONAL", // জাতীয় বিশ্ববিদ্যালয়
  GOVT: "GOVT", // সরকারি কলেজ
  NON_GOVT: "NON_GOVT", // বেসরকারি কলেজ
};
