export const NOTIFICATION_TYPES = {
  LIKE: "LIKE",
  COMMENT: "COMMENT",
  REPLY: "REPLY",
  FRIEND_REQUEST: "FRIEND_REQUEST",
  FRIEND_ACCEPT: "FRIEND_ACCEPT",
  FOLLOW: "FOLLOW",
  MENTION: "MENTION",
  SYSTEM: "SYSTEM",
  GROUP_APPROVE: "GROUP_APPROVE",
  GROUP_ROLE_UPDATE: "GROUP_ROLE_UPDATE",
};
